# fly.toml app configuration file generated for backend-sparkling-sea-8773 on 2025-04-18T12:56:23+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

# Production app configuration
app = 'backend-STAGING'
primary_region = 'cdg'

[build]
  dockerfile = 'docker/Dockerfile'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1 # Keep at least 1 machine running for production
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1